apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-api
  labels:
    app: fraud-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-api
  template:
    metadata:
      labels:
        app: fraud-api
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: fraud-api
        image: IMAGE_PLACEHOLDER
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: S3_ENDPOINT_URL
          value: "https://storage.yandexcloud.net"
        - name: YC_CLEAN_BUCKET_PATH
          value: "s3a://mlops-2025-dz3/clean/model"
        - name: YC_CLEAN_BUCKET_AK
          valueFrom:
            secretKeyRef:
              name: s3-creds
              key: access-key
        - name: YC_CLEAN_BUCKET_SK
          valueFrom:
            secretKeyRef:
              name: s3-creds
              key: secret-key
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "3Gi"
            cpu: "1000m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 40
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: fraud-api
spec:
  selector:
    app: fraud-api
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer
